# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'ssa-asb-azagents'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: DownloadSecureFile@1
  name: caCertificate
  inputs:
    secureFile: 'iPhoneDeveloper_NLOK_29June_2021.p12'

- script: |
    echo Installing $(caCertificate.secureFilePath) to the trusted CA directory...   
    cd ~/Library/Keychains
    ls
    security create-keychain -p 'test' test.keychain
    security list-keychains -d user -s $(security list-keychains -d user | sed -e s/\"//g) test.keychain-db
    security unlock-keychain -p 'test' test.keychain
    security import $(caCertificate.secureFilePath) -k test.keychain -P 'SYMCnorton9PT'
    security import $(caCertificate.secureFilePath) -k test.keychain -A
    ls

