# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'ssa-asb-azagents'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: DownloadSecureFile@
  name: caCertificate
  inputs:
    secureFile: 'iPhoneDeveloper_NLOK_29June_2021.p12'

- script: |
    echo Installing $(caCertificate.secureFilePath) to the trusted CA directory...   
    cd $(caCertificate.secureFilePath)
    ls

